
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  // Accès direct (pas le helper env() de prisma/config) : celui-ci lève une
  // erreur bloquante dès que DATABASE_URL est absent, y compris pour des
  // commandes qui n'en ont pas besoin comme `prisma generate` (utilisée au
  // build). La valeur reste bien requise au runtime pour toute commande qui
  // interroge réellement la base (migrate, db push, le client généré...).
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
